6aseurl = "https://insom.github.io/"
languageCode = "en-ie"
title = "Shameless Self Promotion"
canonifyurls = true

theme = "minimo"

disqusShortname = ""
googleAnalytics = ""
Paginate = 5

[params]
  description = "Filling the blank spaces with content is hard."
  dateFormat = "2006, Jan 2"
  copyrightOwner = "Aaron Brady"
  copyrightStartYear = "2016"
  favicon = "favicon.ico"
  hideEntryNavigation = false
  customCSS = ["css/custom.css"]
  customJS = ["js/custom.js"]

[params.seo]
  # Title Separator: - – — · • * ⋆ | ~ « » < >
  titleSeparator = "•"

[params.opengraph]
  [params.opengraph.facebook]
    admins = ""
    appid = ""

[taxonomies]
  category = "categories"
  tag = "tags"

[social]
  facebook = ""

[author]
  name = "Aaron Brady"

[author.social]
  github = "insom"
  twitter = "insom"

[permalinks]
  page = "/:slug/"

#[[menu.main]]
#  name = "Repo"
#  weight = -70
#  identifier = "repository"
#  url = "https://github.com/MunifTanjim/minimo"

# Language Configuration
defaultContentLanguage = "en"

[languages]
  # edit this block for your own language
  [languages.en]
    lang = "en"
    languageName = "English"
    weight = 1
